"""Flight service for retrieving and managing flight data."""

from datetime import datetime, timezone
from typing import Optional

from src.ingestion.fallback import generate_synthetic_flights
from app.backend.models.flight import FlightPosition, FlightListResponse


def _determine_flight_phase(
    altitude: float, vertical_rate: float, on_ground: bool
) -> str:
    """Determine the flight phase based on flight parameters."""
    if on_ground:
        return "ground"
    if altitude < 3000 and vertical_rate > 2:
        return "takeoff"
    if altitude < 3000 and vertical_rate < -2:
        return "landing"
    if vertical_rate > 2:
        return "climb"
    if vertical_rate < -2:
        return "descent"
    return "cruise"


class FlightService:
    """Service for managing flight data retrieval."""

    def __init__(self):
        """Initialize the flight service."""
        self._cache: Optional[FlightListResponse] = None

    async def get_flights(self, count: int = 50) -> FlightListResponse:
        """
        Get current flight positions.

        For development, returns synthetic data generated by the fallback module.

        Args:
            count: Number of flights to retrieve.

        Returns:
            FlightListResponse with flight positions.
        """
        # Generate synthetic flight data using the existing fallback module
        raw_data = generate_synthetic_flights(count=count)

        flights = []
        for state in raw_data.get("states", []):
            # Parse OpenSky state vector format
            altitude = state[7] if state[7] is not None else 0.0
            vertical_rate = state[11] if state[11] is not None else 0.0
            on_ground = state[8] if state[8] is not None else False

            flight = FlightPosition(
                icao24=state[0],
                callsign=state[1].strip() if state[1] else None,
                latitude=state[6],
                longitude=state[5],
                altitude=altitude,
                velocity=state[9],
                heading=state[10],
                on_ground=on_ground,
                vertical_rate=vertical_rate,
                last_seen=state[4],
                data_source="synthetic",
                flight_phase=_determine_flight_phase(altitude, vertical_rate, on_ground),
            )
            flights.append(flight)

        response = FlightListResponse(
            flights=flights,
            count=len(flights),
            timestamp=datetime.now(timezone.utc),
        )

        self._cache = response
        return response

    async def get_flight_by_icao24(self, icao24: str) -> Optional[FlightPosition]:
        """
        Get a specific flight by ICAO24 address.

        Args:
            icao24: The ICAO24 address to search for.

        Returns:
            FlightPosition if found, None otherwise.
        """
        # Get fresh data if no cache
        if self._cache is None:
            await self.get_flights()

        if self._cache:
            for flight in self._cache.flights:
                if flight.icao24 == icao24:
                    return flight

        return None


# Singleton instance
_flight_service: Optional[FlightService] = None


def get_flight_service() -> FlightService:
    """
    Dependency function for FastAPI injection.

    Returns:
        FlightService singleton instance.
    """
    global _flight_service
    if _flight_service is None:
        _flight_service = FlightService()
    return _flight_service
