resources:
  apps:
    airport_digital_twin:
      name: airport-digital-twin-${bundle.target}
      description: "Airport Digital Twin - Real-time flight visualization"
      source_code_path: ..
      resources:
        - name: sql-warehouse
          sql_warehouse:
            id: b868e84cedeb4262
            permission: CAN_USE
        - name: inpainting-endpoint
          serving_endpoint:
            name: airport-dt-aircraft-inpainting-${bundle.target}
            permission: CAN_QUERY
