airport: SEA
start_date: '2025-06-16'
arrivals: 3500
departures: 3500
duration_hours: 168
time_step_seconds: 10.0
seed: 42
output_file: simulation_output/simulation_sea_7day.json
scenario_file: scenarios/sea_atmospheric_river_windstorm.yaml
