airport: SFO
start_date: "2025-06-16"
arrivals: 500
departures: 500
duration_hours: 24
time_step_seconds: 2.0
seed: 42
output_file: simulation_output/simulation_sfo_1000_thunderstorm.json
scenario_file: scenarios/sfo_summer_thunderstorm.yaml
